services:
  telemt:
    image: exalon/telemt:v1
    container_name: telemt
    restart: unless-stopped
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./telemt.toml:/etc/telemt.toml:ro
    ports:
      - "4433:4433/tcp"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,size=16m
